pipeline {
  agent any

  environment {
    IMAGE_NAME     = "smurf-go"
    DOCKERHUB_USER = "muddanadevops"
  }

  stages {

    stage('Checkout') {
      steps {
        git 'https://github.com/sindhumgithub/smurf-website.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
        docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:latest app/
        '''
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
          echo $PASS | docker login -u $USER --password-stdin
          docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        '''
      }
    }
  }
}
